### ISSUE TITLE
Not working anymore ...

### ISSUE THREAD

**Issue by MrMic** [NastuzziSamy/ulauncher-translate#1]
Hi,

Can you fix it ?
When I try for example: "trans fr:en salut" It still  stay in "Loading ..."

Rgds,

**Comment by NastuzziSamy** [comment]
Hi, 
It is working for me, do you have any clue or do you know why it is not working ?

Thank you !

**Comment by MrMic** [comment]
If I knew why it is not working, I have already told you ...
I have installed the extension like others, and yours is 
not working : that all I know ...

**Comment by NastuzziSamy** [comment]
Have you installed translate python package ? 

It is working for me and others, until you have more information, this issue is closed.

**Comment by MrMic** [comment]
So easy to close without solving anything.

**Comment by NastuzziSamy** [comment]
1. Who do you think you are ?
2. You are the only one with this issue, detail what you have so I can solve the "supposed issue"
3. I asked you a question, you did not answer
4. It is a community package, people give their time to develop for people like you, who can't take 5 min of their time trying to solve their issue or help the community.

And well done, you are the first person I will block on Github. Have a nice holiday.
