### ISSUE TITLE
Doubt about translation performance

### ISSUE THREAD

**Issue by StebanDev** [NastuzziSamy/ulauncher-translate#2]
Hi, first I wanna thank you for the great work developing this extension but I want to know if there is something I can do to improve the translation speed because in console I got the word translated in less than a second but through ulauncher it takes more than 3 seconds, sometimes even 10.

I am using Ulauncher v5 and lastest extension version.

![image](https://user-images.githubusercontent.com/13490436/111016547-955cc380-837c-11eb-9e80-20520ab1c9bd.png)

**Comment by NastuzziSamy** [comment]
Hi, thank you !

I updated the README and how it is translated. Now, when you stop typing, it will wait 0.5s before starting translation.
